# Generated by Django 5.0.4 on 2024-04-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.category')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.recipe')),
            ],
        ),
    ]
